name: Pipeline CI

on:
  push:
  pull_request:

jobs:
  validar-e-construir:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v4

      - name: Verificar arquivo HTML
        run: test -f index.html

      - name: Verificar arquivo CSS
        run: test -f style.css

      - name: Construir imagem Docker
        run: docker build -t meu-primeiro-pipeline .
